=== 2020-NFP121-1000f-PascalFares/C2/GLG/C2_06_SpringXMLJSON/08_spring_xml_json/00_demo_simples/src/main/resources/glg203/ressources/demoSchema/dessin.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="dessin"
           elementFormDefault="qualified">
    <!-- Dessin un peu plus complexe que dessin_1 : suite de cercles ou de segments.-->
    <xs:element name="dessin">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="cercle" >
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element  name="x" type="xs:decimal"/>                
                                <xs:element  name="y" type="xs:decimal"/>                
                                <xs:element  name="r" type="xs:decimal"/>                
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="segment" >
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element  name="x0" type="xs:decimal"/>                
                                <xs:element  name="y0" type="xs:decimal"/>                
                                <xs:element  name="x1" type="xs:decimal"/>                
                                <xs:element  name="y1" type="xs:decimal"/>                                                
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 2020-NFP121-1000f-PascalFares/C2/GLG/C2_06_SpringXMLJSON/08_spring_xml_json/00_demo_simples/src/main/resources/glg203/ressources/demoSchema/exempleDessin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ds:dessin
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ds='dessin'
    xsi:schemaLocation='dessin http://deptinfo.cnam.fr/~rosmorse/dessin.xsd'>
     <ds:segment>
        <ds:x0>12</ds:x0>
        <ds:y0>12</ds:y0>
        <ds:x1>12</ds:x1>
        <ds:y1>12</ds:y1>
    </ds:segment>
     <ds:segment>
        <ds:x0>12</ds:x0>
        <ds:y0>12</ds:y0>
        <ds:x1>12</ds:x1>
        <ds:y1>12</ds:y1>
    </ds:segment>
    <ds:cercle>
        <ds:x>10</ds:x>
        <ds:y>10</ds:y>
        <ds:r>20</ds:r>            
    </ds:cercle>
     <ds:segment>
        <ds:x0>12</ds:x0>
        <ds:y0>12</ds:y0>
        <ds:x1>12</ds:x1>
        <ds:y1>12</ds:y1>
    </ds:segment>
   <ds:cercle>
        <ds:x>13</ds:x>
        <ds:y>40</ds:y>
        <ds:r>10</ds:r>            
    </ds:cercle>
    <ds:segment>
        <ds:x0>12</ds:x0>
        <ds:y0>12</ds:y0>
        <ds:x1>12</ds:x1>
        <ds:y1>12</ds:y1>
    </ds:segment>

</ds:dessin>
