=== 2020-NFP121-1000f-PascalFares/C2/GLG/C2_06_SpringXMLJSON/08_spring_xml_json/00_demo_simples/src/main/resources/glg203/ressources/jaxb/person.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="personne">
        <xs:complexType>
            <xs:sequence>
                <xs:element  name="id" type="xs:integer"/>                
                <xs:element  name="nom" >
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>                            
                        </xs:restriction> 
                    </xs:simpleType>
                </xs:element>
                <xs:element name="telephones">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="telephone" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>                    
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="telephone">
        <xs:complexType>
            <xs:sequence>
                <xs:element  name="numero" type="xs:string"/>    
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== 2020-NFP121-1000f-PascalFares/C2/GLG/C2_06_SpringXMLJSON/08_spring_xml_json/00_demo_simples/src/main/resources/glg203/ressources/xml/demoAvecSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<personne
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/Users/rosmord/Documents/MesDocuments/Cours/GLG203-GLG204/XML/exemplesCoursXML/src/glg203/xml/jaxb/person.xsd'>
    <id></id>
    <nom></nom>
    <telephones>
        <telephone>
            <numero></numero>
        </telephone>
        <telephone>
            <numero></numero>
        </telephone>
        <telephone>
            <numero></numero>
        </telephone>
    </telephones>

</personne>
